<html>

<head>

	 <?= $this->include('frontend/partial/head') ?>
</head>

<body>
    <?= $this->include('frontend/partial/menu') ?>
<?php 
$this->db = \Config\Database::connect();
$request = \Config\Services::request();
?>

    <main>
        <section class="breadcum--block">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcum__main">
                    <ul class="d-flex align-items-center">
                        <li>Home</li>
                        <li class="d-flex"><img class="in__svg" src="<?php echo base_url('assets/frontend/'); ?>/img/down-arrow.svg" alt="Arrow"></li>
                        <li class="active"><?php echo $request->uri->getSegment(2); ?></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="joyari__content--block">
    <div class="container">
        <h2>Exchange & Return</h2>
       <hr>
    <h4>Introduction</h4>
    <p>This document (“Terms and Conditions”) is an electronic record in terms of Information Technology Act, 2000 and rules there under, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and terms and conditions for access or usage of joyari.com (“Website”) and all associated Web sites linked to joyari.com. This Website, including Mira Jewels’ sites around the world, are owned and operated by Mira Jewels and its affiliates, (collectively ‘the Site’ and ‘Company’). By using our Website, you accept these Terms and Conditions as well as Website’s Privacy Policy (which is hereby incorporated by reference herein) in full; accordingly, if you disagree with these Terms and Conditions or any part of these Terms and Conditions, you must not use our Website. These Terms and Conditions govern your use of, and any purchase from the Site, and constitute an agreement between you and Mira Jewels. These Terms and Conditions along with the Privacy Policy extends to both users who visit the Website but do not transact business on the Website ("Users / Guests") as well as users who are registered with the Website to transact business on the Website ("Members"). Joyari.com reserves the right to change these Terms and Conditions from time to time without any obligation to inform you or any third party. It is your responsibility to look through them as often as possible. All rights, including copyright, in this Website are owned by or licensed to Mira Jewels. Any use of this Website or its contents, including copying or storing it in whole or part is prohibited without the permission of Mira Jewels. If you have any queries about these Terms and Conditions or have any comments or complaints on or about our website, please email us at connect@joyari.com.</p>
   
   <h4>Definitions and Interpretations</h4>
   <p>"Jewelry" means ornaments made of gold, silver, copper etc, and / or platinum, either plain or studded with diamond or other gems that are available for sale on our website. Reference to “we” and “us” is a reference to Mira Jewels and joyari.com. Reference to “you” and “User” is a reference to the visitor on joyari.com website as well as the purchaser of jewelry from the website. “Contract / Agreement” means the contract / agreement between us for the sale and purchase of the Jewelry which incorporates these Terms & Conditions.</p>
   
   <h4>Eligibility Criteria</h4>
   <p>Any use / purchase / contract from / with this Website are not intended for users under the age of 18, unless permitted under applicable local laws (“Permissible Age”). Accordingly, by using our Website or agreeing to these Terms and Conditions, you warrant and represent to us that you are of the Permissible Age. We do not knowingly provide any service of the Website from users or solicit information from anyone below the Permissible Age. If we become aware that any person below the Permissible Age is using the Website, we will restrict the access of the Website to such user as soon as possible. If you believe that any person under the Permissible Age is using the Website or we might have any information of a user under the Permissible Age, please contact us at connect@joyari.com.</p>
   
    <h4>Online Services</h4>
   <p>This Website provides services to purchase Jewelry, customized and/or readymade Jewelry. Certain Services available on this Website are for the use of Members only. Some items may appear slightly larger or smaller than actual size due to screen defaults and photography techniques. Sometimes the items may be represented larger than the actual size in order to clearly show details or smaller than the actual size in order to show the entire item. The Company shall not be liable for any legal action on this account alleging mis-representation.</p>
   
    <h4>Registration</h4>
   <p>Users may register on the Website to become Members prior to the completion of any transaction on the Website. Guest checkout’s will be provided with a user account on completion of purchase. To register onto the Website the User will have to provide Personal Information (as defined in the Privacy Policy), including but not limited to full name, e-mail, contact number and contact address, which will be used for verification purposes. Registration is only a one time process and if the Member has previously registered, he/she shall login / sign into his / her account.</p>
   
    <h4>User Account, Password And Security</h4>
   <p>You will receive a password and account designation upon completing the Website's registration process. You are responsible for maintaining the confidentiality of the password and account and are fully responsible for all activities that occur under your password or account. You agree to (a) immediately notify joyari.com of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session. Joyari.com cannot and will not be liable for any loss or damage arising from your failure to comply with these guidelines.</p>
   
    <h4>Communications</h4>
   <p>When you use the Website or send emails or other data, information or communication to us, you agree and understand that you are communicating with us through electronic records and you consent to receive communications via electronic records from us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise, as we feel suitable.</p>
   
    <h4>Pricing Policy</h4>
   <p>Prices include GST (Goods and Services Tax). While Website strives to provide accurate product and pricing information, pricing or typographical errors may occur. Joyari.com cannot confirm the price of a product until after you order. In the event that a product is listed at an incorrect price or with incorrect information due to an error in pricing or product information, Joyari.com shall have the right, at our sole discretion, to refuse or cancel any orders placed for that product, unless the product has already been dispatched. In the event that an item is mis-priced, Joyari.com may, at its discretion, either contact you for instructions or cancel your order and notify you of such cancellation. Unless the product ordered by you has been dispatched, your offer will not be deemed accepted and Joyari.com will have the right to modify the price of the product and contact you for further instructions using the e-mail address provided by you during the time of registration, or cancel the order and notify you of such cancellation. In the event that Joyari.com accepts your order the same shall be debited to your payment account and duly notified to you by email that the payment has been processed. The payment may be processed prior to Joyari.com dispatch of the product that you have ordered. If we have to cancel the order after we have processed the payment, but before the product is dispatched to you, the said amount will be reversed back to your payment account. We strive to provide you with the best prices possible on joyari.com as well as in all our stores. However, sometimes a price online does not match the price in a store. In our effort to be the lowest price provider in your particular geographic region, store pricing will sometimes differ from online prices. Prices and availability are subject to change without notice. For International deliveries, additional duties and taxes may be applicable for the ordered items as per your country’s regulations, which will be billed separately to you by the courier company at the time of delivery. Prices of the products on the Website are subject to change without notice, and can vary from piece to piece, and from time to time, depending on the price of raw materials at the time of production. Gold, Silver and precious stones are commodities, with market fluctuations beyond our control. Occasionally, a piece will sell, and then be recreated at a later date with a difference in price. This simply reflects the market value of the raw materials and may not mean that we have increased our mark-up.</p>
   
    <h4>Essential Service</h4>
   <p>•	All products are with certificate of authenticity. We will certify our diamond by our strict quality protocol as well as by other international renowned certification body as per the case may be.<br/>
    •	Free shipping insurance cover is available for the product purchased by you which shall give additional surety of delivery of the product by due care.<br/>
    •	All products which are available on our website, are Made to Order after the successfully completion of placing the order by you. Hence, ordered product will normally be dispatched within 8-12 working days.<br/>
    •	We have manufacturing experience of more than forty years. Hence, we can deliver quality product at the best price.<br/>
</p>
   
    <h4>Privacy Policy</h4>
   <p>Protection of your privacy is fundamental for us. We understand clearly that you and your personal information is one of the Company’s most important assets. We store and process your personal information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under. Our current privacy policy is available at www.joyari.com/Privacy-Policy. If you object to your personal information being used in this way, you must not use the Website.</p>
   
    <h4>Order Of Products</h4>
   <p>All products and information displayed on the Website constitute an invitation to offer. Your order for purchase constitutes your offer, which shall be subject to the Terms and Conditions as listed herein. We reserve the right to accept or reject your offer in part or in full. Our acceptance of your order will take place upon dispatch of the product(s) ordered. Dispatch of all the product(s) ordered, may or may not happen at the same time, in such a scenario that portion of the order which has been dispatched will be deemed to have been accepted by us and the balance would continue to be on offer to us and we reserve the right to accept or reject such balance order. No act or omission of Joyari.com prior to the actual dispatch of the product(s) ordered will constitute acceptance of your offer. If you have provided us with your email address, we will notify you by email as soon as possible to confirm receipt of your order and email you again to confirm dispatch and therefore acceptance of the order. All products are subject to availability. We reserve the right to limit the quantity of products we supply, supply only part of an order or to divide up orders. We will inform you if we are unable to fulfil your order.</p>
   
   <h4>Online Payment</h4>
   <p>All payments on the Website are securely processed through our payment gateway partner. We accept most major credit and debit cards including Visa, MasterCard and American Express or via PayPal. We may accept bank transfers upon special request at our sole discretion. You can contact our customer care for the same. We endeavour to ensure confirmation of ordered item(s), availability and shipping before processing your order transaction. You will be advised by e-mail if we are unable to complete your order. In the event the bank fails to honour any payment transaction made by a User towards an order, Joyari.com shall have the right to refuse to ship the order to the User without any liability whatsoever.</p>
   
   <h4>Discount Codes</h4>
   <p>We may offer promotional discount codes, which may apply in respect of orders made at website. These codes may only be used on full-price items and cannot be used in conjunction with any other offer or discounts. We retain the right to withdraw or cancel a discount or promotion at any time. We also hold the right to refuse.</p>
   
   <h4>Shipping & Delivery</h4>
   <p>•	The User has to specify the address and details of the person who will collect the shipment at the time of purchase. At the time of placing the order, the User has to state full name of the recipient as stated in his / her government approved photo identification.<br/>
•	At the point of delivery the recipient, in order to collect the physical product, may have to provide any one of the following government approved<br/> 
    &nbsp;&nbsp;&nbsp;photo identification card,<br/>
	&nbsp;&nbsp;&nbsp;Driving License,<br/>
	&nbsp;&nbsp;&nbsp;Passport.<br/>
•	The logistic agent may require verifying the photo ID and name of the recipient while delivering the jewelry.<br/>
•	The logistic agent may also note down the details of the government photo identification.<br/>
•	The recipient of the package must cooperate with the logistic agent in providing the required and valid copies of his / her government approved photo identification, etc.<br/>
•	Recipient accepting delivery should not accept deliveries where the box or packaging has been tampered with or if the box is empty.<br/>
•	If the recipient is not available at the time of delivery, the logistic company would try and deliver the item a couple of times before returning the same to Joyari.com. In such an event, the order would be treated as cancelled. All costs for re-shipment and handling in the case of non-delivery to the User shall be chargeable to the User.<br/>
•	Delivery guarantee is subject to terms and conditions of the logistic company. Any inconsistency in name or address will result in non delivery of the product.<br/>
•	For International buyers, orders are shipped and delivered through registered international logistic companies only. For domestic buyers, orders are shipped through registered domestic logistic companies only.<br/>
•	Joyari.com is not liable for any delay in delivery by the logistic company and only guarantees to hand over the consignment to the logistic company within the time committed.<br/>
•	Joyari.com is in no way responsible for any damage to the product while in transit to the recipient.<br/>
•	In the event that a non-delivery occurs on account of a mistake by you (i.e. wrong name or address or any other wrong information) any extra cost incurred by Joyari.com for redelivery shall be payable by you.<br/>
•	We may contact you for additional information if required. After your order is shipped, you may obtain a logistic tracking number by logging in and checking the Order Info. Logistic tracking number (if any).<br/>
</p>
   
   <h4>Returns & Replacements</h4>
   <p>•	Jewelry purchased from the Website can be returned only by calling Mira Jewels at +91-9574559955 within thirty (30) days from delivery of the item(s), subject to conditions detailed hereafter.<br/>
•	In the event the User has purchased a wrong product size, eg. say a wrong ring size, Mira Jewels will resize the product (say the ring), cost of which shall be borne by the User. Mira Jewels will manufacture the same product as per his/her size and will deliver it within 15 working days.<br/>
•	All logistic and shipping costs incurred by the Company for returns shall be borne by the User.<br/>
•	Customized jewelry cannot be returned once the order is confirmed and processed by Joyari.com.<br/>
•	Conditions for return:<br/>
1.	All items must be returned in the same (un used and un damaged) condition as delivered by Joyari.com, along with the original invoice and certificate if any.<br/>
2.	If any item returned shows signs of wear or if it is engraved, altered, resized or damaged in any other manner, it shall not be accepted for return.<br/>
3.	Custom orders with engraving, special ring size etc. cannot be accepted for return, refund or exchange.<br/>
4.	All shipping and handling expenses shall be chargeable to the User.<br/>
5.	All requests for return of product have to be placed within thirty (30) days from the date of delivery. No return requests after thirty (30) days from delivery will be processed.<br/>

</p>
   
    <h4>Faulty Goods</h4>
   <p>•	Goods are classified as faulty if they are received damaged, or where a manufacturing fault occurs within one month of purchase. Please note that items that are damaged as a result of wear and tear are not considered to be faulty.<br/>
•	If you would like to exchange a faulty item, please be aware that we can only replace it for the same product in the same colour and style, subject to availability. Where possible, we will offer to repair faulty items.<br/>
</p>
   
    <h4>Risk And Ownership</h4>
   <p>•	The risk of loss or damage to Goods passes to you upon delivery.<br/>
•	Ownership in all Goods remains with us until full payment of all amounts due to us has been received from you.<br/>
•	You will be responsible for the safe custody and insurance of all Goods in your possession.<br/>
•	You have no right to re-sell any Goods until payment has been received in full by us.<br/>
</p>
   
    <h4>User Obligations</h4>
    <h5>BY USING THIS WEBSITE YOU REPRESENT AND WARRANT THAT:</h5>
   <p>•	You are 18 years of age or older and that your use of the Website and / or Services shall not violate any applicable law or regulation.<br/>
•	All registration information you submit is truthful and accurate and that you agree to maintain the accuracy of such information.<br/>
•	Your registration as a “User” is solely for your personal and non-commercial use. Any use of this Website or its content other than for personal purposes is prohibited.<br/> 
•	Your personal and non-commercial use of this Website shall be subjected to the following restriction (i) you may not modify any content of the Website, including but not limited to, any public display, description, performance, sale, rental, pricing of the product; (ii) you may not decompile, reverse engineer, or disassemble the content, or (c) remove any copyright, trademark registration, or other proprietary notices from the content. You further agree not to access or use this Website in any manner that may be harmful to the operation of this Website or its content.<br/>
•	You will not (a) use any product or service available on the Website and / Services for commercial purposes of any kind, or (b) advertise or sell any products, services or otherwise (whether or not for profit), or solicit others (including, without limitation, solicitations for contributions or donations) or use any public forum for commercial purposes of any kind, or (c) use the Website and / or Services in any way that is unlawful, or harms Joyari.com or any other person or entity, as determined in the sole discretion of Joyari.com.<br/>
•	You will not post, submit, upload, distribute, or otherwise transmit or make available any software or other computer files that contain a virus or other harmful component, or otherwise impair or damage the Website and / or Services or any connected network, or otherwise interfere with any person or entity's use or enjoyment of the Website and / or Services.<br/>
•	You will not engage in any form of antisocial, disrupting, or destructive acts, including "flaming," "spamming," "flooding," "trolling," "phishing" and "griefing" as those terms are commonly understood and used on the Internet.<br/>
•	You will not delete or modify any content of the Website and / or Services, including but not limited to, legal notices, disclaimers or proprietary notices such as copyright or trademark symbols, logos, that you do not own or have express permission to modify. <br/>
•	You understand that you, and not joyari.com, is responsible for all electronic communications and content sent from your computer to us and you must use the website for lawful purposes only.<br/>
•	Joyari.com cannot and will not assure that other users are or will be complying with the foregoing rules or any other provisions of this Terms of Use, and, as between you and Joyari.com, you hereby assume all risk of harm or injury resulting from any such lack of compliance. <br/>
•	You acknowledge that when you access a link that leaves the Website, the site you will enter into is not controlled by Joyari.com and different terms of use and privacy policy may apply. By accessing links to other sites, you acknowledge that Joyari.com is not responsible for those sites. Joyari.com reserves the right to disable links from third-party sites to the Website, although Joyari.com is under no obligation to do so.<br/>
</p>
   
    <h4>Restrictions</h4>
   <p>Joyari.com reserves the right, at our sole discretion, to limit the quantity/value of the items purchased by you and such restrictions may be applicable to orders placed by the same account, the same credit/debit card, and also to orders that use the same billing and/or shipping address. We will provide notification to the customer should such limits be applied. Joyari.com reserves the right, at our sole discretion, to prohibit sales to any one as it may deem fit.</p>
   
    <h4>Cancellation by Joyari.com</h4>
   <p>There may be certain orders that we are unable to accept and must cancel. We reserve the right, at our sole discretion, to refuse or cancel any order for any reason. Some situations that may result in your order being cancelled include limitations on quantities available for purchase, inaccuracies or errors in product or pricing information, or problems identified by our credit and fraud avoidance department. We may also require additional information or verification/s before accepting any order. We will inform you if the entire order or any portion of your order is cancelled or if additional information is required to accept your order. If your order is cancelled after your credit/debit card has been charged, the said amount will be reverted back in your card account. We will seek authorization on your card for the aggregate amount of the order placed by you; however, we may charge your card (capture) only with the amount corresponding to the actual portion of the order that we are able / willing to fulfil, and any associated shipping charges/taxes and levies etc. Any surplus amount, for which we might have originally sought and received an authorization on your card from your Card Issuer, if not captured by us in the time period stipulated by our Merchant Banker, will not be captured/ charged. If however the same is charged to your card/bank account in error, we will refund it as soon as the same is realized by us or brought to our notice, whichever is sooner. Joyari.com reserves the right to capture/charge your card to the full or partially authorized amount for the concerned order.</p>
   
    <h4>Sale and Promotion</h4>
    <h5>All offers for sale on the Website shall be subject to the following conditions:</h5>
   <p>•	The products under the sale will available only till availability of stock with Joyari.com. Duration of sale is in the sole discretion of Joyari.com and it reserves the right to extend or terminate the sale, without further information at any point of time.<br/>
•	The products under the sale may be removed/changed/added by Joyari.com and the discounted prices can also be changed, at sole discretion of Joyari.com.<br/>
•	In case of any further query regarding the sale, please email customer care at connect@joyari.com.<br/>
•	com reserves the right, at any time, to amend/add/remove/modify (in whole or part) any of the terms & conditions of sale, or to replace, wholly or in part, any promotion by another promotion, whether similar to that promotion or not, or to withdraw it altogether, and Mira Jewels’ decision in this regard shall be final and requires no intimation to the customer of any sort.<br/>
</p>
   
   <h4>Losses</h4>
   <p>Mira Jewels and joyari.com will not be responsible for any business loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) or any other indirect or consequential loss that is not reasonably foreseeable to both you and us when you commence using the website.</p>
   
   <h4>Events Beyond our Reasonable Control</h4>
   <p>Joyari.com will not be held responsible for any delay or failure to comply with our obligations under these conditions if the delay or failure arises from any cause which is beyond our reasonable control. This condition does not affect your statutory rights.</p>
   
   <h4>Disclaimer</h4>
   <p>•	The information contained in this website is for general information purposes only. The information is provided by Mira Jewels and while we endeavour to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.<br/>
•	In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.<br/>
•	Through this website you are able to link to other websites which are not under the control of Mira Jewels. We have no control over the nature, content and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorsement of the views expressed within them.<br/>
•	Every effort is made to keep the website up and running smoothly. However, Joyari.com takes no responsibility for, and will not be liable for, the website being temporarily unavailable due to technical issues beyond our control.<br/>
•	The details of the products or product specifications (for instance weight, colour, handwork details, size, etc.) quoted with the product displays are only fairly approximate values. While every endeavour has been made to accurately reproduce colours, there may be minor variations in colour of the actual product because of the nature of product, weather at the time of differences in display output due to lighting and digital photography and colour settings and capabilities of monitors. A customer must place an order keeping in mind this minor variation in colour as seen on a computer screen against the actual colour of the product received.<br/>
•	Packaging of the product may also vary from the packaging of the product displayed in the website.<br/>
</p>
   
   <h4>Limitation of Liability</h4>
   <p>Joyari.com has made this service available to use as a matter of convenience. Joyari.com expressly disclaims any claim or liability arising out of uploading of any obscene, vulgar or pornographic images, photograph or a picture or altering or distorting the images available under this service in an obscene, vulgar or pornographic manner. User agrees and acknowledges that user shall be solely responsible for user's conduct and that Joyari.com reserves the right to terminate your rights to use the service immediately, notwithstanding penal provisions under the Indian cyber laws or any other allied laws enacted by the government of India or any other statutory, legislative or regulatory authority authorized in this regard from time to time. In no event shall Joyari.com be liable for any direct, indirect, punitive, incidental, special or consequential damages or for any damages whatsoever including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with the use or performance of the joyari.com sites/services for interrupted communications, delay, lost data or lost profits arising out of or in connection with this agreement, even if Joyari.com has been advised of the possibility of damages, or inability to use the joyari.com sites/services or related services, the provision of or failure to provide services, or for any information, software, products, services and related graphics obtained through the joyari.com sites/services, or otherwise arising out of the use of the joyari.com sites/services, whether based on contract, tort, negligence, strict liability or otherwise, even if Joyari.com or any of its suppliers has been advised of the possibility of damages. Joyari.com does not endorse in anyway any advertisers / contents of advertisers on its WebPages.</p>
   
   <h4>Copyright & Trademark</h4>
   <p>Joyari.com, together with its licensors, reserves all intellectual property rights in all text, programs, products, processes, technology, content, photographs, designs and other materials, which appear on this joyari.com Website. Access to this Website does not authorize anyone to use any name, logo or mark in any manner. All materials, including images, text, illustrations, designs, icons, photographs, programs, music clips or downloads, video clips and written and other materials that are part of this Website (collectively, the 'Contents') are intended solely for personal, non-commercial use. You may download or copy the Contents and other downloadable materials displayed on the Website for your personal use only. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You will not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the Contents of the Website or any related software. All software used on this Website is the property of the Website or its suppliers and they are protected by Indian and international copyright laws. Except where expressly stated to the contrary all persons (including their names and images), third party trademarks and images of third party products, services and/or locations featured on this Website are in no way associated, linked or affiliated with Joyari.com and you should not rely on the existence of such a connection or affiliation. Any trademarks/names featured on this Website are owned by the respective trademark owners.</p>
   
   <h4>Profanity Policy</h4>
   <p>Joyari.com prohibits the use of language that is racist, hateful, sexual or obscene in nature. This policy extends to your submissions, postings and all other areas of the Website that another user may view. Please report any violations of this policy for review to the grievance officer mentioned in these terms and conditions. If a feedback comment; or any communication made between users on the Website; or email communication between Users contain profanity, please review our feedback removal policy and submit a request for action/removal.</p>
   
   <h4>Termination</h4>
   <p>These Terms and Conditions are effective unless and until terminated by either you or Joyari.com. You may terminate these Terms and Conditions at any time by informing us in writing at connect@joyari.com that you no longer wish to be associated with this Website, provided that you discontinue any further use of this Website. We may terminate these Terms and Conditions at any time and may do so immediately without notice, and accordingly deny you access to the Website. Such termination will be without any liability to the Website. Upon any termination of these Terms and Conditions by either you or Joyari.com, you must promptly destroy all materials downloaded or otherwise obtained from this Website, as well as all copies of such materials, whether made under these Terms and Conditions or otherwise. Our right to any Comments shall survive any termination of these Terms and Conditions. Any such termination of these Terms and Conditions shall not cancel your obligation to pay for the product(s) already ordered from the Website or affect any liability against you that may have arisen under the User Agreement.</p>
   
   <h4>Governing Law And Jurisdiction</h4>
   <p>These Terms and Conditions shall be construed in accordance with the applicable laws of India. The Courts at Surat, Gujarat shall alone have exclusive jurisdiction in any proceedings arising out of this agreement.</p>
   
   <h4>Modification of Terms and Conditions of Service</h4>
   <p>Joyari.com reserves the right at any time to modify the Terms and Conditions without any prior notification to you. Subsequent to any such modification of the Terms and Conditions, we will inform you of the modifications in the Terms and Conditions through e-mail at the e-mail address provided by you while registering on the Website. You can access the latest version of the Terms and Conditions at any given time on the Website. You should regularly review the Terms and Conditions on the Website. In the event the modified Terms and Conditions is not acceptable to you, you undertake to discontinue using the service. However, if you continue to use the service, you shall be deemed to have agreed and accepted to the modified Terms and Conditions and you undertake to abide by the modified Terms and Conditions.</p>
   
   <h4>Arbitration</h4>
   <p>If any dispute arises between you and the Company during your use of the Website or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of this Terms and Conditions, and the privacy policy or the documents they incorporate by reference, the dispute shall be referred to a sole Arbitrator who shall be an independent and neutral third party identified by the Company. The place of arbitration shall be Surat. The Arbitration & Conciliation Act, 1996, shall govern the arbitration proceedings. The arbitration proceedings shall be in the English language.</p>
   
   <h4>General</h4>
   <p>None of the provisions of these Terms and Conditions shall be deemed to constitute a partnership or agency between you and the Company and you shall have no authority to bind the Company in any manner whatsoever. Except as explicitly stated otherwise, any notices shall be given by postal mail to Joyari.com Corporate Office at 2nd floor, Amber Appartement, Opp. Sadhana Society, Mini Bazar, Varachha Road, Surat 395006, India or to the email address you provide to us during the registration process (in your case). Notice shall be deemed given 24 hours after email is sent, unless the sending party is notified that the email address is invalid. Alternatively, we may give you notice by certified mail, postage prepaid and return receipt requested, to the address provided to us during the registration process. In such case, notice shall be deemed given 3 days after the date of mailing. If any clause of this Agreement shall be deemed invalid, void or for any reason unenforceable, such clause shall be deemed severable and shall not affect the validity and enforceability of the remaining clauses of the Terms and Conditions. These Terms and Conditions sets forth the entire understanding and agreement between you and us with respect to the subject matter hereof. In the Company's sole discretion, it may transfer its rights and obligations (under these Terms and Conditions without your prior express consent). If you breach these Terms and Conditions, and the privacy policy or the documents they incorporate by reference, and we take no action against you, we will still be entitled to use our rights and remedies in any other situation where you breach the aforesaid. The Company may terminate these Terms and Conditions at any time. Without limiting the foregoing, the Company shall have the right to immediately terminate any passwords or accounts of the user in the event of any conduct by the user which the Company, in its sole discretion, considers to be unacceptable, or in the event of any breach by the user of these Terms and Conditions. Notwithstanding any other provisions of these Terms and Conditions, or any general legal principles to the contrary, any provision of these Terms and Conditions that imposes or contemplates continuing obligations on a party will survive the expiration or termination of these Terms and Conditions.</p>
   
   <h4>Indemnity</h4>
   <p>You shall indemnify and hold harmless Joyari.com, its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys’ fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms and Conditions, privacy policy and other policies, or your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</p>
   
   <h4>Limitation Of Damages</h4>
   <p>In no event shall Joyari.com or any of its subsidiaries or affiliates be liable to any entity for any direct, indirect, special, consequential or other damages (including, without limitation, any lost profits, business interruption, loss of information or programs or other data on your information handling system) that are related to the use of, or the inability to use, the content, materials, and functions of this Website or any linked Website, even if Joyari.com is expressly advised of the possibility of such damages.</p>
   
   <h4>Grievance Officer</h4>
   <p>In accordance with Information Technology Act, 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below Name: Mr. Yogesh Devshibhai Raval Address: 2nd floor, Amber Appartement, Opp. Sadhana Society, Mini Bazar, Varachha Road, Surat 395006 Email: connect@joyari.com Time: Monday to Friday 10.00 a.m. to 5.00 p.m. and Saturday 10.00 a.m. to 2.00 p.m. Not available on Sundays and Indian national/ public holidays</p>
   
   <h4>Contact Information</h4>
   <p>For questions, please contact us at connect@joyari.com or call on our helpline no. (+91) 95745 59955. Helpline numbers are only available between 10.00 am to 6.15 pm (IST), Monday to Saturday and are not available on Sundays and Indian national/ public holidays.</p>
   
  
    </div>
</section>
 <?= $this->include('frontend/partial/footer') ?>
       <?= $this->include('frontend/partial/js') ?>
       </body>

</html>

